### ISSUE TITLE
OddsPortal-dropping-odds: odznaczanie spotkania

### ISSUE THREAD

**Issue by overcq** [overcq/betting#6]
Spotkanie odznaczone ma się nigdy więcej nie pojawić na stronie.
Ponieważ pojawianie się na stronie nie jest zależne od skryptu, ale od strony, to faktycznie trzeba takie spotkania ukrywać, gdy się pojawią na stronie. By je ukrywać, trzeba pamiętać identyfikator spotkania.
Pytanie jest, jak długo ten identyfikator spotkania przetrzymywać w pamięci. Przypuszczalnie do upływu daty spotkania. A ta data jest zapisana w pierwszej kolumnie, ale w formie w połowie słownej. Więc potrzeba interpretować tę datę.
Dodatkowo można dodać automatyczne usuwanie spotkań zaznaczonych, gdy minęła data.

**Comment by njczyziu** [comment]
Jeżeli spotkanie nie zostało odznaczone z jakiś względów, to niech znika zaraz po zakończeniu. Nie potrzeba przechowywać spotkań, które i tak już są nieaktualne.
